version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: your_postgres_user
      DB_PASSWORD: your_postgres_password
      DB_NAME: multi_finance
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: multi_finance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
